version: '3.7'
services:
  consul-server:
    image: consul:latest
    networks:
      - app-networks
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  rabbit:
    image: rabbit-consul-integrated
    networks:
      - app-networks
    depends_on:
      - consul-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        - RABBITMQ_ERLANG_COOKIE='rabbitmq'
    deploy:
      replicas: 3

  spring-service:
    build:
      context: .
    depends_on:
      - rabbit
    networks:
      - app-networks
    ports:
      - "8888"

networks:
  app-networks:
    driver: bridge
