version: '3.7'
services:
  consul-server:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  consul-client:
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  spring-service:
    build:
      context: .
    ports:
      - "8888"
