CREATE TABLE IF NOT EXISTS docker_instances (
id INT AUTO_INCREMENT PRIMARY KEY,
container_id VARCHAR(200) NOT NULL,
image_name VARCHAR (200) NOT NULL,
status VARCHAR(200) NOT NULL,
last_status_update TIMESTAMP NOT NULL
);